steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/${_PROJECT_ID}/firebase', '.' ]
images:
- 'gcr.io/${_PROJECT_ID}/firebase'
- name: 'gcr.io/cloud-builders/npm'
  args: [ 'install' ]
  dir: 'functions'
- name: 'gcr.io/proveit-muffins/firebase'
  args: [ 'deploy', '-P', 'proveit-muffins', '--token', '${_FIREBASE_TOKEN}']
